### ISSUE TITLE
Admin logout button bug

### ISSUE THREAD

**Issue by yuvrajsab** [csdu/sankalan-portal#27]
after logging out from admin user then log into normal user we are getting 403 error, The problem is with "ajax-button" component which is not working correctly. The quick solution would be to use traditional form request instead of ajax.

**Comment by rumansaleem** [comment]
Can you explain what is wrong with ajax-button component? It is the same thing.

**Comment by yuvrajsab** [comment]
Try doing the following in **admin.blade.php**.
*use this:*
```
<form action="{{ route('logout') }}" method="post">
    @csrf
    <button type="submit" class="btn is-red font-normal">Logout</button>
</form>
```
*instead of this:*
```
<ajax-button action="{{ route('logout') }}" method="post" @success="reload()" class="btn is-red font-normal">Logout</a>
```

**Comment by rumansaleem** [comment]
That is fine. Create a PR for this. But also try to find out what is wrong with the component why is it not working the same way?

**Comment by rumansaleem** [comment]
Well, I guess we just need to tweak the reload function a little bit. Currently, after successful logout. We are reloading the same page, which is admin's dashboard. Now, since the user has been logged out they are redirected to login page. After logging in they are redirected to the page where they intended to go, that would be admin dashboard in this case.
